Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using EstructurasDatos_Lab03.Models;
using EstructurasDatos_Lab03.Clases;
using LibreriaGenerica.Estructuras;
using Microsoft.VisualBasic.FileIO;
using Microsoft.AspNetCore.Hosting;
using PagedList;

namespace EstructurasDatos_Lab03.Controllers
{
    public class PedidosController : Controller
    {
        public static ArbolAVL<NodoFarmacos> ArbolBusqueda = new ArbolAVL<NodoFarmacos>();
        public static List<NodoFarmacos> FarmacosVacios = new List<NodoFarmacos>();
        public static PedidosModel NuevoPedido = new PedidosModel();
        public static string RutaBase;
        public static string RutaArchivoAux;
        private IWebHostEnvironment Environment;
        public void Editar(NodoFarmacos NodoAuxFarmaco, int Borrar)
        {
            int NumeroLinea = 1;
            string Linea;
            using (StreamReader ArchivoLectura = new StreamReader(RutaBase))
            {
                using (StreamWriter ArchivoLimpiar = new StreamWriter(RutaArchivoAux))
                {
                    ArchivoLimpiar.WriteLine(ArchivoLectura.ReadLine());
                    ArchivoLimpiar.Flush();
                }
                using (StreamWriter ArchivoEscritura = new StreamWriter(RutaArchivoAux, true))
                {
                    do
                    {
                        Linea = ArchivoLectura.ReadLine();
                        if (NumeroLinea == NodoAuxFarmaco.ID)
                        {
                            int Posicion = Linea.Length - 1;
                            if (Borrar > 10)
                                Posicion = Linea.Length - 2;
                            Linea = Linea.Substring(0, Posicion);
                            Linea += NodoAuxFarmaco.Inventario;
                        }
                        ArchivoEscritura.WriteLineAsync(Linea);
                        ArchivoEscritura.Flush();
                        NumeroLinea++;
                    } while (Linea != null);

                }
            }
            System.IO.File.Copy(RutaArchivoAux, RutaBase, true);
        }
        public ActionResult Reabastecer(int? Pagina)
        {
            List<NodoFarmacos> ListaFamacos = FarmacosVacios;
            if (Pagina == 0)
                Pagina = 1;
            int Cantidad = 12;
            int NumeroPagina = (Pagina ?? 1);
            return View("ReabastecimientoFar", ListaFamacos.ToPagedList(NumeroPagina, Cantidad));
        }

        public ActionResult RealizarReabastecimiento()
        {
            Random GenerarRandom = new Random();
            foreach (NodoFarmacos item in FarmacosVacios)
            {
                int NumeroRandom = GenerarRandom.Next(1, 15);
                item.Inventario = NumeroRandom;
                ArbolBusqueda.Add(item, item.BuscarNombre);
                Editar(item, NumeroRandom);
            }
            FarmacosVacios.Clear();
            ViewBag.Farmacos = ArbolBusqueda.Mostrar();
            return View("Index");
        }

        public Farmacos ObtenerFarmaco(NodoFarmacos NodoAuxFarmaco)
        {
            Farmacos FarmacoMostrar = new Farmacos();
            using (TextFieldParser Archivo = new TextFieldParser(RutaBase))
            {
                Archivo.TextFieldType = FieldType.Delimited;
                Archivo.SetDelimiters(",");
                while (!Archivo.EndOfData)
                {
                    try
                    {
                        if (NodoAuxFarmaco.ID == Archivo.LineNumber - 1)
                        {
                            string[] Texto = Archivo.ReadFields();
                            FarmacoMostrar.ID = Convert.ToInt32(Texto[0]);
                            FarmacoMostrar.Nombre = Texto[1];
                            FarmacoMostrar.Descripcion = Texto[2];
                            FarmacoMostrar.CasaProductora = Texto[3];
                            FarmacoMostrar.Precio = Convert.ToDouble(Texto[4].Substring(1));
                            FarmacoMostrar.Inventario = Convert.ToInt32(Texto[5]);
                            Archivo.ReadToEnd();
                        }
                    }
                    catch (Exception)
                    {
                    }
                    Archivo.ReadLine();
                }
            }
            return FarmacoMostrar;
        }

        public PedidosController(IWebHostEnvironment _environment)
        {
            Environment = _environment;
        }
        // GET: Pedidos
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult RealizarPedidos()
        {
            ViewBag.Farmacos = NuevoPedido.PedidoFarmacos;
            return View(NuevoPedido);
        }
        public ActionResult ConfirmarPedido()
        {
            NuevoPedido = new PedidosModel();
            return View("Index");
        }

        //Vista Importar  AgregarFarmaco
        public ActionResult CargarFarmacos(int? pagina)
        {

            return View("ImportarFarmacos");
        }

        public ActionResult Paginacion(int? Pagina)
        {
            List<NodoFarmacos> ListaFamacos = ArbolBusqueda.Mostrar();
            if (Pagina == 0)
                Pagina = 1;
            int Cantidad = 12;
            int NumeroPagina = (Pagina ?? 1);
            return View("InventarioFarmacos", ListaFamacos.ToPagedList(NumeroPagina, Cantidad));
        }

        public ActionResult BuscarFarmacos(string Texto, IFormCollection collection)
        {
            NuevoPedido.NombreCliente = collection["NombreCliente"];
            NuevoPedido.Nit = collection["Nit"];
            NuevoPedido.Direccion = collection["Direccion"];
            NodoFarmacos NodoAuxFarmaco = new NodoFarmacos();
            NodoAuxFarmaco.Nombre = Texto;
            NodoAuxFarmaco = ArbolBusqueda.Get(NodoAuxFarmaco, NodoAuxFarmaco.BuscarNombre);
            if (NodoAuxFarmaco != null)
            {
                return View("AgregarFarmaco", ObtenerFarmaco(NodoAuxFarmaco));
            }
            else
            {
                ViewBag.Farmacos = NuevoPedido.PedidoFarmacos;
                return View("RealizarPedidos", NuevoPedido);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarFarmaco(IFormCollection collection)
        {
            NodoFarmacos EditarFarmaco = new NodoFarmacos();
            EditarFarmaco.Nombre = collection["Nombre"];
            EditarFarmaco = ArbolBusqueda.Get(EditarFarmaco, EditarFarmaco.BuscarNombre);
            int Descontar = int.Parse(collection["Inventario"]);
            Farmacos FarmacoAux = ObtenerFarmaco(EditarFarmaco);
            if (EditarFarmaco.Inventario >= Descontar && Descontar >= 0)
            {
                //Borra el nodo de un farmaco exitente
                if (NuevoPedido.PedidoFarmacos.Exists(x => x.Nombre == EditarFarmaco.Nombre))
                {
                    FarmacoAux = NuevoPedido.PedidoFarmacos.Find(x => x.Nombre == EditarFarmaco.Nombre);
                    NuevoPedido.PedidoFarmacos.Remove(FarmacoAux);
                }
                //Resta la cantidad a Inventario
                EditarFarmaco.Inventario -= Descontar;
                //Edita el Nodo en el Arbol
                ArbolBusqueda.Edit(EditarFarmaco, EditarFarmaco.BuscarNombre);
                //Agrego la Cantidad Comprada al producto
                FarmacoAux.CantidadComprada += Descontar;
                FarmacoAux.PrecioTotal = Math.Round(FarmacoAux.Precio * Descontar, 2);
                NuevoPedido.PedidoFarmacos.Add(FarmacoAux);
                NuevoPedido.Total = 0;
                foreach (Farmacos item in NuevoPedido.PedidoFarmacos)
                {
                    NuevoPedido.Total += item.PrecioTotal;
                }
                if (EditarFarmaco.Inventario == 0)
                {
                    FarmacosVacios.Add(EditarFarmaco);
                    ArbolBusqueda.Delete(EditarFarmaco, EditarFarmaco.BuscarNombre);
                }
                Editar(EditarFarmaco, Descontar);
                ViewBag.Farmacos = NuevoPedido.PedidoFarmacos;
                return View("RealizarPedidos", NuevoPedido);
            }
            else
            {
                return View("AgregarFarmaco", FarmacoAux);
            }
        }

        [HttpPost]
        public IActionResult ImportarFarmacos(IFormFile ArchivoCargado)
        {
            if (ArchivoCargado.FileName.Contains(".csv"))
            {
                string Ruta = Path.Combine(Environment.WebRootPath, "Documentos/");
                RutaArchivoAux = Ruta + "AchivoAux.csv";
                RutaBase = Path.Combine(Ruta, "ArchivoOriginal.csv");
                if (!Directory.Exists(Ruta))
                    Directory.CreateDirectory(Ruta);
                using (FileStream stream = new FileStream(Path.Combine(Ruta, "ArchivoOriginal.csv"), FileMode.Create))
                {
                    ArchivoCargado.CopyTo(stream);
                }
                using (FileStream stream2 = new FileStream(Path.Combine(Ruta, "AchivoAux.csv"), FileMode.Create))
                {
                    ArchivoCargado.CopyTo(stream2);
                }
                using (TextFieldParser Archivo = new TextFieldParser(RutaBase))
                {
                    Archivo.TextFieldType = FieldType.Delimited;
                    Archivo.SetDelimiters(",");
                    while (!Archivo.EndOfData)
                    {
                        string[] Texto = Archivo.ReadFields();
                        NodoFarmacos NodoFarmaco = new NodoFarmacos();
                        try
                        {
                            NodoFarmaco.ID = Convert.ToInt32(Texto[0]);

Views/Pedidos/AgregarFarmaco.cshtml
@model EstructurasDatos_Lab03.Clases.Farmacos

@{
    ViewData["Title"] = "AgregarFarmaco";
}

<h1>Agregar Fármaco</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarFarmaco">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" >
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control-plaintext alert-dark " />
                <input asp-for="Nombre" class="form-control-plaintext alert-dark " hidden/>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control-plaintext alert-dark " disabled />
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control-plaintext alert-dark" disabled />
            </div>
            <div class="form-group">
                <label asp-for="Inventario" class="control-label">Cantidad a Comprar</label>
                <input asp-for="Inventario" class="form-control" />
                <span asp-validation-for="Inventario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inventario" class="control-label">Cantidad Diponible</label>
                <input asp-for="Inventario" class="form-control-plaintext alert-dark" disabled />
            </div>
            <div class="form-group">
                <label asp-for="CasaProductora" class="control-label"></label>
                <input asp-for="CasaProductora" class="form-control-plaintext alert-dark" disabled />
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control-plaintext alert-dark" disabled />
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Pedidos/ImportarFarmacos.cshtml
@{
    ViewData["Title"] = "ImportarFarmacos";
}

<div class="text-center">
    <h1>Cargar Inventario</h1>
</div>
<h5>
    Ingrese el Archivo:
</h5>

<form method="post" enctype="multipart/form-data" asp-controller="Pedidos" asp-action="ImportarFarmacos">

    <input type="file" class="form-control-file" name="ArchivoCargado" />
    <br />
    <input type="submit" value="Agregar" class="form-control-file" />

</form>
<br />
<p>
    <a asp-action="Index" class="btn btn-outline-dark">Regresar</a>
</p>

Views/Pedidos/Index.cshtml
@{ ViewData["Title"] = "Index"; }
<div class="text-center">
    <h1>Bienvenido</h1>
</div>

<a asp-action="CargarFarmacos" class="btn btn-outline-primary">Cargar Invetario</a>
<a asp-action="RealizarPedidos" class="btn btn-outline-primary">Realizar Pedidos</a>
<a asp-action="Paginacion" class="btn btn-outline-primary">Inventario</a>
<a asp-action="Reabastecer" class="btn btn-outline-primary">Reabastecer fármacos</a>

Views/Pedidos/InventarioFarmacos.cshtml
@model PagedList.IPagedList<EstructurasDatos_Lab03.Clases.NodoFarmacos>

@{ ViewData["Title"] = "InventarioFarmacos"; }

<h1>Inventario Fármacos</h1>

<p>
    <a asp-action="Index" class="btn btn-outline-dark">Regresar</a>
</p>


<table class="table table-striped">
    <thead class="">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Inventario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr class="">
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Inventario)
            </td>
      
        </tr>
}
    </tbody>
</table>

    <div class="bg";>
        @if (Model.HasPreviousPage)
        {
@Html.ActionLink("<<", "Paginacion", new { Pagina = 1 });
@Html.Raw(" ");
@Html.ActionLink("<Anterior", "Paginacion", new { Pagina = Model.PageNumber - 1 });

}
else
{
@:<<
@Html.Raw(" ");
@:< Anterior
}
        -- Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
        of  @Model.PageCount --
        @if (Model.HasNextPage)
        {
@Html.ActionLink(" Siguiente>", "Paginacion", new { Pagina = Model.PageNumber + 1 });
@Html.Raw(" ");
@Html.ActionLink(">>", "Paginacion", new { Pagina = Model.PageCount });

}
else
{
@: Siguiente>
@Html.Raw(" ");
@:>>
}
    </div>

Views/Pedidos/ReabastecimientoFar.cshtml
@model PagedList.IPagedList<EstructurasDatos_Lab03.Clases.NodoFarmacos>

@{
    ViewData["Title"] = "Reabastecimiento";
}

<h1>Reabastecimiento</h1>
<p>
    <a asp-action="Index" class="btn btn-outline-dark" style="position:absolute; left: 200px; top: 120px">Regresar</a>
</p>
<p>
    <a asp-action="RealizarReabastecimiento" class="btn btn-outline-success">Reabastecer</a>
</p>

<table class="table table-striped">
    <thead class="">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Inventario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="thead-light">
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Inventario)
                </td>
     
            </tr>
        }
    </tbody>
</table>
<div class="bg";>
    @if (Model.HasPreviousPage)
    {
        @Html.ActionLink("<<", "Paginacion", new { Pagina = 1 });
        @Html.Raw(" ");
        @Html.ActionLink("<Anterior", "Paginacion", new { Pagina = Model.PageNumber - 1 });

    }
    else
    {
        @:<<
        @Html.Raw(" ");
        @:< Anterior
    }
    -- Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
    of  @Model.PageCount --
    @if (Model.HasNextPage)
    {
        @Html.ActionLink(" Siguiente>", "Paginacion", new { Pagina = Model.PageNumber + 1 });
        @Html.Raw(" ");
        @Html.ActionLink(">>", "Paginacion", new { Pagina = Model.PageCount });

    }
    else
    {
        @: Siguiente>
        @Html.Raw(" ");
        @:>>
    }
</div>

Views/Pedidos/RealizarPedidos.cshtml
@model EstructurasDatos_Lab03.Models.PedidosModel

@{
    ViewData["Title"] = "RealizarPedidos";
}

<h1>Realizar Pedidos</h1>
<p>
    <a asp-action="Index" class="btn btn-outline-dark">Regresar</a>
</p>

<hr />
<div class="row">
    <div class="col-md-4">
        <form class="form-inline my-2 my-lg-0" asp-controller="Pedidos" asp-action="BuscarFarmacos">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="NombreCliente" class="form-control" style="position:absolute; left: 20px; top:0px; width: 300px;" placeholder="Nombre Del Cliente" required />
                <span asp-validation-for="NombreCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Direccion" style=" position: absolute;left: 335px;  top: 0px" placeholder="Dirección" class="form-control" required />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Nit" class="form-control" style="position:absolute; left: 575px; top:0px" placeholder="Nit" required />
                <span asp-validation-for="Nit" class="text-danger"></span>
            </div>
            <div>
                <a asp-action="ConfirmarPedido" class="btn btn-outline-success" style="position:absolute; left: 825px; top:0px; width: 300px;" role="button">Realizar Pedido</a>
            </div>
            <table class="table table-striped" style="position:absolute; left: 0px; top:50px; width: 74em">
                <thead class="">
                    <tr>
                        <th>
                            Cantidad Comprada
                        </th>
                        <th>
                            Nombre
                        </th>
                        <th>
                            Descripcion
                        </th>
                        <th>
                            Casa Productora
                        </th>
                        <th>
                            Precio
                        </th>
                        <th>
                            Precio Total
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (EstructurasDatos_Lab03.Clases.Farmacos item in ViewBag.Farmacos)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CantidadComprada)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Descripcion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CasaProductora)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Precio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PrecioTotal)
                            </td>
                        </tr>
                    }
                </tbody>
                <thead class="">
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col">Total</th>
                        <th scope="col"><input asp-for="Total" class="form-control alert-dark" /></th>
                    </tr>
            </table>
            <div class="form-group" style="position:absolute; left: 800px; top:-70px">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="Texto">
                <button class="btn btn-outline-info my-2 my-sm-0" style="position:absolute; left: 200px; top:0px" type="submit">Buscar</button>

            </div>
        </form>
    </div>

</div>